module.exports = {
  pathPrefix: "/",
  title: "Dave Clark",
  titleAlt: "Dave Clark",
  description: "Retired consultant - collection of in-depth articles on Microsoft Power Platform.",
  url: "https://daveclark.io",
  siteUrl: "https://daveclark.io",
  siteLanguage: "en",
  logo: "/images/logo.png",
  banner: "/images/banner-med.png",
  favicon: "src/images/favicon.png",
  shortName: "DaveClarkIO",
  author: "Dave Clark",
  themeColor: "#373435",
  backgroundColor: "#f2f0e6",
  twitter: "@daveclarkio",
};
