module.exports = {
  pathPrefix: "/",
  title: "Dave Clark",
  titleAlt: "Dave Clark",
  description: "Power Platform content and tutorials for professionals.",
  url: "https://daveclark.io",
  siteUrl: "https://daveclark.io",
  siteLanguage: "en",
  logo: "src/images/flavicon.png",
  banner: "src/images/flavicon.png",
  favicon: "src/images/favicon.png",
  shortName: "DaveClarkIO",
  author: "Dave",
  themeColor: "#373435",
  backgroundColor: "#f2f0e6",
  twitter: "@daveclarkio",
};
